# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ea42b9c09fa339e1a3fee4614a8c86de077034dd842e8582134d40498cb7d6de98753ead1f09964ebb3988d3cfdbf6496a9e57a86336e7e69562eb3d60df1bb

test:
  secret_key_base: d33e5f625aaf7dd9920db4c87c2cad592b1e42c2c61b595a689a24857a1277d51c1eb22ef3e8a83bed5fd4f404fe6ab5c8e4d475eb75d11ba9b9791edc52b179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
